### ISSUE TITLE
bug: Weird light / shadows behavior

### ISSUE THREAD

**Issue by Gameplayer13** [RyanJGray/aliasIsolation#21]
**Describe the bug**
Hi Ryan, first, thank you very much for this fork of Alias Isolation !

I have some weird light / shadows effects happening when the mod is enable. Please see attached video showing the issue : https://streamable.com/2vpgjv

On the video there's both a ON and OFF Alias Isolation setup, as yo can see when the mod is turned OFF the shadow glitches do not happens, then when turned back ON it does.

Thank you for your hard work on this !

**Setup details**
 - Game store: Steam Version
 - OS version:  Windows 11 Pro Up to date
 - GPU model: RX 6700 XT
 - GPU driver and version: 23.5.2
 - Mod version last release 

Addendum : I cited you and linked your mod in my Steam moding guide for Alien isolation

**Comment by Gameplayer13** [comment]
Don't know if that can be considered as a separate issue than the one mentionned by @AnticOwl considering i'm not using DSR nor any upscaling method

**Comment by RyanJGray** [comment]
> Don't know if that can be considered as a separate issue than the one mentionned by @AnticOwl considering i'm not using DSR nor any upscaling method

Thanks for the report!

I'd say it's the same issue as what @AnticOwl reported, I have a pretty good idea what the cause is, I believe one of my optimisations to the mod has caused some unexpected shadow jittering.

I need some more time to properly come up with a fix for it, as undoing my changes causes a decent performance hit again, but maybe that's not so bad.

I'll keep you posted 😄

**Comment by AnticOwl** [comment]
Thank you!

**Comment by leonwschr** [comment]
I'm currently trying to play the game with your fork of aliasIsolation and I also have an AMD GPU, specifically an RX 7800 XT. Unfortunately there seem to be a lot of flickering lights/flickering shadows for me too with your latest version (v1.1.2), but with the previous version (v1.1.1) this doesn't seem to be an issue, but the performance is pretty bad. In case you're still working on this mod, I'd appreciate an answer, otherwise ignore this and just have a nice day!

**Comment by RyanJGray** [comment]
Hey, thanks for the details!

I have been working on an update for this off and on, and I am currently in my last year of university, which takes most of my time at the moment :(

The flickering only seems to happen in certain areas, but I think I've worked out how to balance my optimisations so that it doesn't cause this issue.

I'll have an update soon, perhaps in the next couple of weeks, when I get some spare time away from uni. work.

**Comment by dadavis1992** [comment]
I'm getting this issue as well with v1.1.2

Any chance of a fix coming soon? Wondering if I should revert to 1.1.1

**Comment by RyanJGray** [comment]
> I'm getting this issue as well with v1.1.2
> 
> Any chance of a fix coming soon? Wondering if I should revert to 1.1.1

I'm working on this at the moment, sorry it's taking so long, had a lot going on IRL that took priority!

**Comment by AnticOwl** [comment]
> > I'm getting this issue as well with v1.1.2
> > Any chance of a fix coming soon? Wondering if I should revert to 1.1.1
> 
> I'm working on this at the moment, sorry it's taking so long, had a lot going on IRL that took priority!

Take your time mate.
