### ISSUE TITLE
Weird distortion/smearing of textures near the edges all around the screen. 

### ISSUE THREAD

**Issue by deathray1611** [RyanJGray/aliasIsolation#28]
![20240328212055_1](https://github.com/RyanJGray/aliasIsolation/assets/73653366/56b380a4-e93a-4b1a-94dd-52dbe3d3fc7f)

This one has been an issue for me on both your mod and the og Alias Isolation for the longest time (when they worked lol. Alot of the time they would freeze or crash too. The 1.1.3 of this one for example, which was thankfully fixed). It's not game breaking (thankfully) and is barely noticeable when you are actually playing, but when it comes to taking screenshots can look quite jarring as you can see here. 

Not much to add other than that one time the mod worked flawlessly (it was the og one I think), and that was after I discovered that my SSD was borked (had damaged cluster. Probably was a restored one, because it came with a PC. Yes, the PC was bought, not put together by myself, amateurish I know), and I changed it for a new one, installing my OS there, while putting everything else on the completely fresh HDD I had (it was sitting in a box unpacked for months when I was considering whether to build PC myself or buy it). But after several months, I tried to launch the game and then it all went to hell again - freezing on launch and all, Reinstalled the mod and it worked, but this artifact returned.

Specs:
 - Game store: Steam
 - OS version: Windows 10 Pro 22H2 10.0.19045.4170
 - GPU model: Sapphire Radeon RX 470 
 - GPU driver and version: AMD (Adrenaline) 24.1.1
 - CPU: 12-Core Intel Xeon E5-2670 v3, 2700 MHz (27 x 100)
 - Mod version: 1.1.4.

Additional note:
Still cannot download 2024-01 Security Update for Windows 10 Version 22H2 for x64-based Systems (KB5034441), but I don't remember if I started having issues with Alias when that started happening but pretty sure it was before that update was even available (or before I tried installing it) 

Also - the current version of the mod voids the in-game cursor with a basic desktop one.

**Comment by RyanJGray** [comment]
Thanks for the very detailed report!

If I understand it right, that looks like Chromatic Aberration, if by smearing, you mean the red-like blurring around the edges of the screen?

You can turn that off in the DELETE menu of Alias, you should double-check it's off in the game settings as well.

I'll probably make Alias force on specific graphics settings in the engine instead of the user needing to manually set them for the mod to work.

It should disappear when Chromatic Aberration is disabled in the mod's DELETE menu, the original author added a custom shader for it, I presume to make it work with TAA properly.

I'm not a huge fan of it as a visual effect, I could probably change it as the default, but I don't honestly know how many people use it.
The default CA intensity does seem excessive.

**Comment by RyanJGray** [comment]
Also yeah, I need to find a way to fix the mouse cursor changing

**Comment by deathray1611** [comment]
Thanks for the instant response!

Yeah, I think that's what it is. The texture just looks "smeared" to me, like they were washed or smth lol. You can see it best by looking at the text (compare the "EMERGENCY" on the save station, and "OVERVIEW" on the either one of the signs. Coincidentally this effect shows itself the worst around text, and bright textures).

Can I ask how to access the Alias Isolation menu? I am using your mod and thought it doesn't have a GUI? Also checked README and it didn't say anything about it either, only how to turn on or disable the mod in run time (which, last time I checked, which I did with 1.1.2 I think, would kinda break the mod if you disabled and then enabled the mod too much and too quickly)

**Comment by deathray1611** [comment]
OMG I am so stupid. You literally access a menu with DELETE. 

And OMG x2 that fixed it! You are a treasure sir, thank you for your amazing mod!

(Btw, please don't change the look of that menu, I REALLY like how old school it looks, weirdly fitting to the game's aesthetic, even if very much distinctly different)

The difference is actually staggering when you compare:

without CA
![20240329131120_1](https://github.com/RyanJGray/aliasIsolation/assets/73653366/aff4f7f7-caca-4de9-a36c-fb45dc3a4808)

with CA
![20240328212055_1](https://github.com/RyanJGray/aliasIsolation/assets/73653366/63fb1fc2-bbdb-42e7-9998-67c84bf8b651)

**Comment by deathray1611** [comment]
You know what I find weird? Why when you use the mod with its CA turned on, it can create this artifact, while when playing without it with the base game settings, it looks fine (bar AA obviously)? Does the mod use its own CA and can "layer" it on top of the game's one, making it more intense?

**Comment by RyanJGray** [comment]
Glad that sorted it out, thanks for the detailed report anyhow!

Lol I was thinking of changing the menu to mimic the colour of the computer terminals in-game, but that's just the default look of the menu library I use, glad you like it!

I do find the mod's default CA intensity to be a bit much, I think that the default setting of `0.5` for CA is too much.

I'll maybe try and tweak it to more closely match what the stock/base-game CA does.

It's probably blurring/smearing too much because the intensity of CA in the mod by default is set a bit too high.
It ends up creating this "blurred" or "smeared" effect in the corners of the screen (the mod's CA shader intentionally reduces CA in the center of the screen to preserve sharpness).
