### ISSUE TITLE
bug: 3DVisionFix / 3DMigoto crash

### ISSUE THREAD

**Issue by RakhimIlkhh** [RyanJGray/aliasIsolation#30]
**Describe the bug**
The game usually crashes when using flamethrower on face huggers. Rarely it crashes with the same error elsewhere.

**How to reproduce**
Set game to use fullscreen, it doesn't crash when in borderless windowed.

**Expected behaviour**
The game should not crash when trying to get a nice face hugger barbeque going.

**Screenshots**
N/A

**Setup details**
 - Game store: Steam
 - OS version: Windows 10 Pro 22H2
 - GPU model: NVIDIA RTX 2080 TI
 - GPU driver and version: NVIDIA 552.44
 - Proton version: N/A
 - Mod version: v1.1.4

**Additional context**
I'm unfortunately using quite a lot of mods so I guess unless the dump file can give some information on this it might be difficult to troubleshoot without going from a vanilla install and adding mods one by one until the issue pops up. Below are the mods I use which I think could cause issues.

Mod list:
3dvisionfix with Helixvision to get stereo image to a Quest 3 VR headset
2x upscaled textures
Bay's Alien Isolation Overhaul V2 (changes radiosity settings)
Improved Graphics

The mod works wonderfully in this setup and have been crash free until I came to the reactor part with the face huggers and then later on the Anesidora. These parts I had to play in borderless windowed mode but unfortunately it performs way worse so I get pretty bad stutters.

[aliasIsolationCrashDump.dmp](https://github.com/RyanJGray/aliasIsolation/files/15441417/aliasIsolationCrashDump.dmp)
[fatalerroraliasisolation.txt](https://github.com/RyanJGray/aliasIsolation/files/15441418/fatalerroraliasisolation.txt)

**Comment by RyanJGray** [comment]
Hey! Thanks for sending in a bug report with the .dmp file, it took some digging but I think I have an idea of what is happening.

I suspect that the crash is being caused by 3dmigoto (called `d3d11.dll` in your game folder) - but this most likely came with the 3dvisionfix mod that you're using.


I see you're using ThirteenAG's Skip Save Confirmation mod too, you're using the included `winmm.dll` which could also be causing problems (this is a very old version of the same loader that I recommend).

Hmm, could you try the below steps?

- Rename your 3dmigoto/3dvisionfix mod's `d3d11.dll` file to `d3d11Hooked.dll`.
- Instead of using the `winmm.dll` loader from the Skip Save Confirmation mod (which has caused issues in the past), use `d3d11.dll` from here https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/Win32-latest/d3d11-Win32.zip
- Remove `winmm.dll` from your game's folder.

This should let aliasIsolation be loaded in the way it prefers, and then the 3D vision stuff should get loaded in a compatible way.

I think you're running into a rare problem with too many things trying to hook into DirectX 11 than usual in varying ways, but using a more up-to-date loader, and renaming the DLLs should hopefully make it a bit more reliable.

I want to try and get the 3D vision mod to work with this mod, you must be mighty brave to play this in VR! :D

Let me know if you need any more help and please keep me posted on your progress!

**Comment by Klemci** [comment]
https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/issues/2

**Comment by RyanJGray** [comment]
> https://github.com/ThirteenAG/AlienIsolation.SkipSaveConfirmationDialog/issues/2

Cheers! Good to know someone has got 3DMigoto working before

**Comment by Rikufdi** [comment]
Sorry I missed this post, I'm away on vacation right now but I will fire up my setup and try your suggestions when I get back home!

**Comment by RyanJGray** [comment]
No worries. Enjoy your vacation, and keep us posted on the results! :D

**Comment by RakhimIlkhh** [comment]
A small update after some tinkering around.

I got the game to run with the latest asi loader and it successfully loading both skipsave and aliasisolation and working in stereoscopic 3d in the quest 3.

 I renamed the stereo3dfix dll to d3d11Hooked.dll as suggested and with the asi loader named to winmm.dll.

I tried using the loader with it named as d3d11.dll and a few others as suggested on that github page but in those cases, it failed to load one or both of the skipsave and aliasisolation asi.

I'm starting a new playthrough and will see if it still crashes in fullscreen when using the flamethrower on facehuggers but it might take a while until I get there. Will update then.

Thanks for the suggestions and help!

**Comment by RyanJGray** [comment]
Glad to hear you got it working, let me know if you still run into issues and I can look into making this scenario a bit more reliable for you!

Hope you enjoy your new playthrough (:

**Comment by RakhimIlkhh** [comment]
Great news!

I got to the reactor part and can report that I've not had a single crash there or anywhere else while in game!

I've been tinkering with this for a long time and playing it in a vr headset in stereoscopic 3d is beyond horrifying. The image quality with proper anti-aliasing and a few mods makes this game truly stand out.

I did a playthrough some years back with the mothervr mod and that is also an excellent way to play it, but you lose some image quality as well as getting some annoying pop-ins.

Thanks again for the help!

**Comment by RyanJGray** [comment]
Great to hear. Thanks for working with me to figure this issue out!

I think I'll turn your discoveries into part of the install instructions for people wanting to use stereoscopic 3D, I will make sure to give credit! (:

As always, let me know if there's any more issues, and I will see what I can do.
