### ISSUE TITLE
bug:  Crashing on Steam with Improved Graphics Mod

### ISSUE THREAD

**Issue by tadpolegaming** [RyanJGray/aliasIsolation#33]
The game now crashes while using the Improved Graphics Mod (https://www.nexusmods.com/alienisolation/mods/19) giving the same hookableOverlayRender error that was occuring on the Epic Games Store port. I actually fixed the crashing by using the 64 bit version of the d3d11.dll rather than the 32 bit one, but Alias is not injecting into the game properly anymore.

**Comment by RyanJGray** [comment]
Hey! Thanks for checking out the mod.

Is there any chance that you could upload the `aliasIsolationCrashDump.dmp` file that gets created when the game crashes?

If you're on Windows, it should exist within `%temp%`, on Proton/Linux it'll be in `.steam/steam/steamapps/compatdata/214490/pfx/drive_c/users/steamuser/Temp`.

When I get that, it'll let me know what caused the crash. I can't imagine the improved graphics mod would conflict, unless you used the installer they provide and not the XML file?

**Comment by tadpolegaming** [comment]
I did manage to get the old version running by disabling the Steam overlay and running the game exe as administrator. No such luck on this one.
[aliasIsolationCrashDump.dmp](https://github.com/user-attachments/files/16842978/aliasIsolationCrashDump.dmp)

**Comment by RyanJGray** [comment]
Hmm, interesting. I'll take a look at the dump file today. I wonder if AIMovieFix (xinput in your game folder) is conflicting with Alias somehow.

**Comment by RyanJGray** [comment]
Ah I think I see what the issue is... did you extract the `mods` folder to your Alien: Isolation install folder (same location as file `AI.exe`)?
The mod hit an exception trying to access a critical shader file.

Your Alien: Isolation game directory should look something like this:
```txt
Alien: Isolation
  * DATA
  * mods
    * aliasIsolation
      * data
        * shaders
        * textures
  * AI.exe
  * aliasIsolation.asi
  * d3d11.dll
```

If the `mods` folder does not exist or contain the expected files included in the release archive, the mod won't work. 

It should have shown you an extra pop-up saying:
> FATAL ERROR - Failed to find critical data file "C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation\mods\aliasIsolation\data\shaders\mainPost_vs.hlsl"!

That is the section where it "crashed" (it force quits the game and creates a dump file to ensure it stops running in a controlled way).

Could you confirm you have a `mods` folder in your A:I folder?

**Comment by tadpolegaming** [comment]
No, I was extracting what was in the mods folder into the game directory. Alias works fine now. Sorry about that.

**Comment by RyanJGray** [comment]
These things happen, it's alright! Glad you got it sorted out, let me know if there's any more issues, and I can take a look for you.
